---
- hosts: localhost
  tasks:
    - name: Test connection to Rubrik 
      test_conn:
        node: "rubrik.demo.com"
        rubrik_user: "foo"
        rubrik_pass: "bar"
        vmware_vm_name: "{{ item.vmware_vm_name }}"
        sla_domain: "Bronze"
    with_items:
      - { vmware_vm_name: 'th-ubu-chef-client' }

