---

- name: Validate the Rubrik Modules
  hosts: local
  connection: local
  vars_files:
    - ./variables.yml

  tasks:

    - name: Rubrik Job Status
      rubrik_job_status:
        provider: "{{ credentials }}"
        job_status_link: "{{ job_status_link }}"